{% set name = "rethinkdb-python" %}
{% set version = "2.4.10.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/rethinkdb/rethinkdb-{{ version }}.tar.gz
  sha256: 3634e03ee13dd637fd7196b80474bf44c64d3eba1dd069ea92b94926702a60bd

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - rethinkdb-import = rethinkdb._import:main
    - rethinkdb-dump = rethinkdb._dump:main
    - rethinkdb-export = rethinkdb._export:main
    - rethinkdb-restore = rethinkdb._restore:main
    - rethinkdb-index-rebuild = rethinkdb._index_rebuild:main
    - rethinkdb-repl = rethinkdb.__main__:startInterpreter

requirements:
  host:
    - looseversion
    - pip
    - python {{ python_min }}
    - setuptools
    - six
  run:
    - looseversion
    - python >={{ python_min }}
    - six
    - tornado
    - trio

test:
  imports:
    - rethinkdb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rethinkdb.com/api/python/
  summary: Python driver for RethinkDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
